---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zitadel-server
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`heritage.varghacsongor.hu`) && Path(`/login`)
      services:
        - name: zitadel
          port: 8080
  tls: {}