apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: generations-heritage

resources:
  - ./certificate.yaml
  - ./secrets.yaml
  - ./ingressRoute.yaml

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts/
    releaseName: postgresql
    namespace: generations-heritage
    version: 16.0.6
    valuesFile: postgres-values.yaml
  - name: zitadel
    repo: https://charts.zitadel.com
    releaseName: zitadel
    namespace: generations-heritage
    version: 8.5.0
    valuesFile: ./values.yaml

patches:
  - target:
      kind: CronJob
    patch: |
      - op: replace
        path: /apiVersion
        value: batch/v1
  - target:
      name: zitadel-setup
      kind: Job
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 4
  - target:
      name: zitadel-setup
      kind: Job
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: Sync
  - target:
      name: zitadel-init
      kind: Job
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 3
  - target:
      name: zitadel-init
      kind: Job
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: Sync