apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cert-job.yaml
  - ./secrets.yaml
  - ./ingressRoute.yaml

helmCharts:
  - name: cockroachdb
    repo: https://charts.cockroachdb.com/
    releaseName: cockroachdb
    version: 12.0.2
    valuesFile: cockroach-values.yaml
  - name: zitadel
    repo: https://charts.zitadel.com
    releaseName: zitadel
    version: 7.10.0
    valuesFile: ./values.yaml
