apiVersion: v1
kind: Secret
metadata:
  name: zitadel-masterkey
  labels:
    secret-generator.cs.sap.com/enabled: "true"
stringData: 
  masterkey: "%generate"
---
apiVersion: v1
kind: Secret
metadata:
  name: cockroach-auth
  labels:
    secret-generator.cs.sap.com/enabled: "true"
stringData:
  cockroach-password: "%generate"
  user-password: "%generate"