zitadel:
  selfSignedCert:
    enabled: true
  masterkeySecretName: zitadel-masterkey
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: zitadel.varghacsongor.hu
    ExternalPort: 443
    Database:
      Postgres:
        Host: postgresql
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          SSL:
            Mode: verify-full
        Admin:
          Username: postgres
          SSL:
            Mode: verify-full

  dbSslCaCrtSecret: zitadel-root-certificate-ca-secret
  dbSslAdminCrtSecret: postgres-cert
  dbSslUserCrtSecret: zitadel-cert

annotations:
  argocd.argoproj.io/sync-wave: "5"
  argocd.argoproj.io/hook: Sync

env:
  - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
    value: admin

  - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: zitadel-masterkey
        key: admin-password

  - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-auth
        key: user-password

  - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-auth
        key: admin-password