zitadel:
  masterkeySecretName: zitadel-masterkey
  configmapConfig:
    ExternalSecure: false
    ExternalDomain: heritage.varghacsongor.hu
    TLS:
      Enabled: false
    Database:
      Cockroach:
        Host: db-cockroachdb-public
        User:
          SSL:
            Mode: verify-full
        Admin:
          SSL:
            Mode: verify-full

  dbSslCaCrtSecret: db-cockroachdb-ca-secret
  dbSslAdminCrtSecret: db-cockroachdb-client-secret
  dbSslUserCrtSecret: db-cockroachdb-zitadel-secret

env:
  - name: ZITADEL_DATABASE_COCKROACH_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cockroach-auth
        key: user-password

  - name: ZITADEL_DATABASE_COCKROACH_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cockroach-auth
        key: cockroach-password