apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authz
spec:
  forwardAuth:
    address: https://gh-authz/auth/
    authResponseHeaders:
      - id
    tls:
      insecureSkipVerify: true