apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ./deployment/cert-issuer.yaml
  - ./deployment/server-transport.yaml
  - ./deployment/project-argo.yaml
  - ./deployment/zitadel-argo.yaml
  - ./deployment/memgraph-argo.yaml
  - ./deployment/auth-service-argo.yaml
  - ./deployment/backend-argo.yaml
