FROM arm64v8/golang:1.22.2-alpine as build

WORKDIR /app

COPY . .

RUN GOOS=linux GOARCH=arm64 go build -o backend

FROM arm64v8/busybox:1.36.1

COPY --from=build /app/backend /app/

CMD [ "/app/backend" ]