apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gh-auth-service
    app.kubernetes.io/name: gh-auth-service
  name: gh-auth-service
spec:
  ports:
  - name: gin
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: gh-auth-service
    app.kubernetes.io/name: gh-auth-service
  type: ClusterIP