apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-auth-service
spec:
  project: generations-heritage-vv
  source:
    repoURL: 'https://github.com/vcscsvcscs/GenerationsHeritage'
    path: deployment/auth-service
    targetRevision: main
    kustomize:
      namespace: generations-heritage
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: generations-heritage
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    