---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-only
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-chain
  namespace: apps
spec:
  chain:
    middlewares:
    - name: https-only
    - name: authn
    - name: authz
