apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: generations-heritage

bases:
  - authZ
  - authN
  - backend
  - memgraph

resources:
  - ./cert-issuer.yaml
  - ./server-transport.yaml
  - ./auth-chain.yaml
