FROM --platform=$BUILDPLATFORM golang:alpine AS build

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY . .

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o auth-service

RUN apk update && apk add ca-certificates && update-ca-certificates

FROM --platform=$TARGETPLATFORM busybox:1.36.1

COPY --from=build /etc/ssl/certs /etc/ssl/certs
COPY --from=build /app/auth-service /app/

CMD [ "/app/auth-service" ]