FROM golang:1.22-alpine as build

WORKDIR /app

COPY . .

RUN GOOS=linux GOARCH=arm64 go build -o auth-service

FROM arm64v8/busybox

COPY --from=build /app/auth-service /app/

CMD [ "/app/auth-service" ]