apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: generations-heritage

resources:
  - ./certificate.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingressRoute.yaml
  - ./horizontalPodAutoScaler.yaml
