apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: memraph-certificate
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - memgraph.generations-heritage.svc.cluster.local
    - memgraph
  subject:
    organizations:
      - Memgraph
      - GenerationsHeritage
  secretName: memgraph-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: default-cluster-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  