image:
  repository: memgraph/memgraph
  tag: "2.20.0"

persistentVolumeClaim:
  storageSize: 2Gi

memgraphConfig:
  - "--also-log-to-stderr=true"

secrets:
  enabled: true
  name: memgraph-secrets
  userKey: USER
  passwordKey: PASSWORD