image:
  repository: memgraph/memgraph

persistentVolumeClaim:
  storageSize: 2Gi
  ## Create a Dynamic Persistant Volume Claim for Configs, Certificates (e.g. Bolt cert ) and rest of User related files
  createUserClaim: true
  userStorageSize: 250Mi

memgraphConfig:
  - "--also-log-to-stderr=true"

secrets:
  enabled: true
  name: memgraph-secrets
  userKey: USER
  passwordKey: PASSWORD