image:
  repository: memgraph/memgraph
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 7687
  targetPort: 7687
  protocol: TCP

persistentVolumeClaim:
  storagePVC: true
  storagePVCSize: 2Gi
  logPVC: true
  logPVCSize: 256Mi

memgraphConfig:
  - "--also-log-to-stderr=true"
  - "--bolt-cert-file=/etc/memgraph/ssl/tls.crt"
  - "--bolt-key-file=/etc/memgraph/ssl/tls.key"

secrets:
  enabled: false
  name: memgraph-secrets
  userKey: USER
  passwordKey: PASSWORD