image:
  repository: memgraph/memgraph
  tag: "2.20.0"

persistentVolumeClaim:
  storageSize: 2Gi

memgraphConfig:
  - "--also-log-to-stderr=true"
  - "--bolt-cert-file=/etc/memgraph/ssl/tls.crt"
  - "--bolt-key-file=/etc/memgraph/ssl/tls.key"

env:
  - name: MEMGRAPH_USER
    valueFrom:
      secretKeyRef:
        name: memgraph-secrets
        key: USER
  - name: MEMGRAPH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: memgraph-secrets
        key: PASSWORD      
