name: Release Auth service to Docker Hub and Deploy to Kubernetes

on:
    push:
#        branches:
#            - 'main'
        paths:
            - "auth-service/**"
            - "deployment/auth-service/**"

jobs:
    docker:
      name: Build and Push Backend image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            context: auth-service
            tags: vcscsvcscs/gheritage-auth-service:latest
    deployment:
      name: Deploy to Kubernetes
      runs-on: ubuntu-latest
      needs: docker
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Deploy to Kubernetes
          uses: actions-hub/kubectl@master
          env:
            KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          with:
            args: apply -k deployment/auth-service/ 