name: Authentication service Continuous Integration
on:
  push:
    paths:
      - "cmd/auth/**"
      - "pkg/**"
jobs:
  lint:
    uses: ./.github/workflows/go_lint.yml
    with:
      working-directory: 'cmd/auth'
  build:
    needs: lint
    uses: ./.github/workflows/go_build.yml
    with:
      working-directory: 'cmd/auth'
  test:
    needs: build
    uses: ./.github/workflows/go_test.yml
    with:
      working-directory: 'cmd/auth'