name: Backend Continuous Integration
on:
  push:
    paths:
      - "backend/**"

jobs:
  lint:
    uses: ./go_lint.yml
    with:
      working-directory: 'backend'
  build:
    needs: lint
    uses: ./go_build.yml
    with:
      working-directory: 'backend'
  test:
    needs: build
    uses: ./go_test.yml
    with:
      working-directory: 'backend'