name: Backend Continuous Integration
on:
  push:
    paths:
      - "backend/**"
jobs:
  lint:
    uses: ./.github/workflows/go_lint.yml
    with:
      working-directory: 'backend'
  build:
    needs: lint
    uses: ./.github/workflows/go_build.yml
    with:
      working-directory: 'backend'
  test:
    needs: build
    uses: ./.github/workflows/go_test.yml
    with:
      working-directory: 'backend'