name: Frontend Continuous Integration
on:
  pull_request:
    paths:
      - "app/**"
jobs:
  lint:
    uses: ./.github/workflows/svelte_lint.yml
    with:
      working-directory: 'app'
  build:
    needs: lint
    uses: ./.github/workflows/svelte_test.yml
    with:
      working-directory: 'app'
