name: Frontend Continuous Integration
on:
  push:
    paths:
      - "cmd/frontend/**"
jobs:
  lint:
    uses: ./.github/workflows/svelte_lint.yml
    with:
      working-directory: 'cmd/frontend'
  build:
    needs: lint
    uses: ./.github/workflows/svelte_build.yml
    with:
      working-directory: 'cmd/frontend'
