name: Frontend Continuous Integration
on:
  push:
    paths:
      - "frontend/**"

jobs:
  lint:
    uses: ./CI/go_lint.yml
    with:
      working-directory: 'backend'
  build:
    needs: lint
    uses: ./CI/go_build.yml
    with:
      working-directory: 'backend'
