name: Frontend Continuous Integration
on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
      
jobs:
  lint:
    uses: ./.github/workflows/svelte_lint.yml
    with:
      working-directory: 'frontend'
  build:
    needs: lint
    uses: ./.github/workflows/svelte_build.yml
    with:
      working-directory: 'frontend'
