on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.x'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get
      
      - name: Build
        run: |
          go build ${{ inputs.working-directory }}