name: Frontend Continuous Integration

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "apps/app**"
      - ".github/workflows/svelte_ci.yml"
      - ".github/workflows/svelte_test.yml"
      - ".github/workflows/svelte_lint.yml"

jobs:
  lint:
    uses: ./.github/workflows/svelte_lint.yml
    with:
      working-directory: 'apps/app'
      
  build:
    needs: lint
    uses: ./.github/workflows/svelte_test.yml
    with:
      working-directory: 'apps/app'
