name: Go Test

on:
  pull_request:
    paths:
      - "cmd/**"
      - "pkg/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.23.x'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get ./...
          
      - name: Run tests
        run: |
          go test ./...